## Joseph Rochelle
## DSC 550 Data mining
## Exercise 1.2


**Assignment:** **2D arrays**

1. Create an array of size [10,50] and use the random function to fill it with integers between 1 and 500 (inclusive). Load it to a DataFrame.

2. Calculate the sum of each row; the sum of each column; and the sum of all entries.

3. Determine the minimum; maximum; average; and standard deviation of all entries.

4. Sort the DataFrame: by rows, by columns, on row 2, on column 2.

In [1]:
# Loading Libraries
import pandas as pd
import random
import numpy as np

In [2]:
#Setting Decimal point preference
np.set_printoptions(precision =2, suppress =True)

In [15]:
#Creating an array using randint as mentioned. 
arr = np.random.randint(1,500,(10,50)) # random numpy array of shape (4,5)
print("Random Array with 1-50 integers with a shape of 10,50:") 
print ()
print (arr)

Random Array with 1-50 integers with a shape of 10,50:

[[ 32 337 139 374 283 293 420  68 264 373 342 301 499 264 429 203 337 264
  164 200 119 200 169 378  63 476  21 191  67 397 215 397 354  54  76 106
  186 177  19 444 372 197 150 473 304 381 251 304 135 187]
 [300 119 434  41 175 301  57 239 214 381 353  48  27 141 280 206 485  13
  457 136 494 431 483  49  86 457 496 210 130 308 173   5  74 439 255 450
  138  14 306 480 146 114 441 411 202  15 347  49 213  42]
 [255 273 113  77 133  55 335 117 390 456 394  25  78 104 235 391  94 229
   61 127 468  94 421  71  69  38  46   8 132 436 412 437 427  95  95 140
   15 476 316 181 336 487  55 492 242 312 285   9 382 101]
 [448 230 350 375 146 382  95 166 330 346 459 167 188 126 210 134 180 146
  355 171 178 338 228 457 411 166 114 187 213 208 268  89 168   2 185 165
  329 297  27  44 456 200 154 232 212  82 469 452 328 164]
 [105  98 335 300 364 329 350 482 166 125 470 282  50  44 253 345 215 214
  141  68 117 302 416  40 124  33 434 143 

In [16]:
#Load to a dataframe
df = pd.DataFrame (arr)
df

0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   32  337  139  374  283  293  420   68  264  373  ...  372  197  150  473   
1  300  119  434   41  175  301   57  239  214  381  ...  146  114  441  411   
2  255  273  113   77  133   55  335  117  390  456  ...  336  487   55  492   
3  448  230  350  375  146  382   95  166  330  346  ...  456  200  154  232   
4  105   98  335  300  364  329  350  482  166  125  ...   73  159    2  189   
5   65   78  126  297  233  289  231  295  319  490  ...   50  298  229   50   
6  396   38  306  325  208  479  475   65  493  343  ...   70   88  100  351   
7  155  232  443  244  246  184  438   74  414   89  ...  171  140  232  348   
8   72   99  233   11  240  373  314  294  284  442  ...   16  201  359  167   
9  466  157  208  486   73   22  303   53  348  317  ...  350  296  296    3   

    44   45   46   47   48   49  
0  304  381  251  304  135  187  
1  202   15  347   49  213   42  
2  242  312  285    9  382  101  
3  212   82  469  452  328  164  
4  206  499  363  196  225   90  
5   16  204   34  483  213  275  
6   63   61  494  483  398   33  
7  413  225  429  496   28  266  
8   32  227  118  342   40  339  
9   50  106  358   84   37  209  

[10 rows x 50 columns]

In [19]:
#Calculating sum of each row and column and entries. 
 

print("\nSum of array : ", np.sum(arr))    ## Sum of total array
print()
print("Sum of array(axis = 0) : ", np.sum(arr, axis = 0)) ## Sum of columns
print()
print("Sum of arrary(axis = 1) : ", np.sum(arr, axis = 1))  ##Sum of rows
  
print("\nSum of array (keepdimension is True): \n", 
      np.sum(arr, axis = 1, keepdims = True)) 


Sum of array :  115983

Sum of array(axis = 0) :  [2294 1661 2687 2530 2101 2707 3018 1853 3222 3362 3743 1960 2131 1868
 2626 2573 2465 2127 2453 2076 2136 2664 3506 2500 1786 2443 2391 2034
 1976 1874 2268 2063 2543 2152 2210 2005 1536 1809 1663 2410 2040 2180
 2018 2716 1740 2112 3148 2898 1999 1706]

Sum of arrary(axis = 1) :  [12449 11865 11020 11827 10131 10126 12981 12233 11888 11463]

Sum of array (keepdimension is True): 
 [[12449]
 [11865]
 [11020]
 [11827]
 [10131]
 [10126]
 [12981]
 [12233]
 [11888]
 [11463]]


In [23]:
#Descriptive statistics of Array

print("Min of array : ", np.min(arr)) 
print("Max of array : ", np.max(arr)) 
print("Mean of array : ", np.mean(arr)) 
print("Standard Deviation of array : ", np.std(arr))  

Min of array :  1
Max of array :  499
Mean of array :  231.966
Standard Deviation of array :  143.6321024144672


In [29]:
#Sorting the array by column 
x =arr[arr[:, 1].argsort()] # Sorted by column
x

array([[396,  38, 306, 325, 208, 479, 475,  65, 493, 343, 430, 276, 460,
        416, 171, 344, 388, 466, 492, 411,   5, 295, 119, 296,  68,  48,
        212, 477, 452,  36,  79, 363, 283, 266, 239, 249, 184,  33,  16,
        138,  70,  88, 100, 351,  63,  61, 494, 483, 398,  33],
       [ 65,  78, 126, 297, 233, 289, 231, 295, 319, 490, 303, 262, 318,
        363, 111,  19, 105, 282, 148,  56,   1, 209, 398, 387, 157,  63,
        396, 176, 164,  48,  72,  75, 146, 278,  59, 338, 302, 101,  83,
        431,  50, 298, 229,  50,  16, 204,  34, 483, 213, 275],
       [105,  98, 335, 300, 364, 329, 350, 482, 166, 125, 470, 282,  50,
         44, 253, 345, 215, 214, 141,  68, 117, 302, 416,  40, 124,  33,
        434, 143,  44,  39,  84, 170, 223, 309, 146, 138,  87, 299, 227,
         18,  73, 159,   2, 189, 206, 499, 363, 196, 225,  90],
       [ 72,  99, 233,  11, 240, 373, 314, 294, 284, 442, 476, 105,  83,
        155, 383, 141,  26, 232, 123, 466, 337, 431, 488, 246, 381, 262,
     

In [31]:
y = arr [ :, arr[1].argsort()] #Sorted by row
y

array([[397, 264, 177, 381, 499, 374, 187, 301, 304, 378, 420, 354,  63,
        197, 337,  67, 200, 186, 264, 372, 215, 283, 304, 203, 191, 135,
        264,  68,  76, 429,  32, 293,  19, 397, 251, 342, 373, 473, 200,
        139,  54, 150, 106, 164, 476, 444, 169, 337, 119,  21],
       [  5,  13,  14,  15,  27,  41,  42,  48,  49,  49,  57,  74,  86,
        114, 119, 130, 136, 138, 141, 146, 173, 175, 202, 206, 210, 213,
        214, 239, 255, 280, 300, 301, 306, 308, 347, 353, 381, 411, 431,
        434, 439, 441, 450, 457, 457, 480, 483, 485, 494, 496],
       [437, 229, 476, 312,  78,  77, 101,  25,   9,  71, 335, 427,  69,
        487, 273, 132, 127,  15, 104, 336, 412, 133, 242, 391,   8, 382,
        390, 117,  95, 235, 255,  55, 316, 436, 285, 394, 456, 492,  94,
        113,  95,  55, 140,  61,  38, 181, 421,  94, 468,  46],
       [ 89, 146, 297,  82, 188, 375, 164, 167, 452, 457,  95, 168, 411,
        200, 230, 213, 171, 329, 126, 456, 268, 146, 212, 134, 187, 328,
     