## Joseph Rochelle
## DSC 550 Data mining
## Week 4 Assignment (Text: Sentiment Analysis)

In [3]:
#Importing libraries
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np
import nltk

#Setting Decimal point preference
np.set_printoptions(precision =2)

In [4]:
#Reading data frame
DailyDf= pd.read_csv('DailyComments.csv')  
DailyDf

Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.
5    Saturday       There' s nothing special happening today.
6      Sunday                      Today is a SUPER good day!

**Manual Sentiment Analizer:**
    
The purpose of this section is to provide the reader with a means to count key words that are meaningful to the researcher. Based off the use cases, there may be a time where evaluating key words and phrases and providing meaning may be important. This section serves as a means to create a column for key words and counts then to summarize the data. 

In [5]:
corpus = DailyDf['comments']

In [6]:
#Vectorizing the words within the corpus, which is our text only comments.

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print("")
print("vectorized words")
print("")
print(vectorizer.get_feature_names())
print("")
print("Identify Feature Words - Matrix View")
print("")
print( X.toarray())


#After turning the vectors into arrays we put it back into a data frame

df = pd.DataFrame({'text' : corpus})

#Check for positive words and negative words based off the schema established. I want to do linguistics connections like very bad super special later. 
#This methods counts the words in our text data frame, adding positive and negative columns. Then, calculated field column totallying.
df['positive1'] = df.text.str.count('good')
df['positive2']= df.text.str.count('special')
df['negative'] = df.text.str.count('bad')
df['TotScore'] = df.positive1 + df.positive2 - df.negative
df['TotCount'] = df.positive1 + df.positive2 + df.negative

print("")
print(df)

# Printing the results in a data frame based off the scoring of sentiment analysis above
Z = sum(df['TotScore'])
Z1= sum(df['TotCount'])
Z2 = Z/Z1


print("")
print("Overall Score:  ",Z)
print("Overall Count:  ",Z1)

# The % of sentiment that was negative. 
#While the researcher does not have to use negative sentiment as the numerator to the total count of words as the denominator, this researcher sought to bring that option to the analysis. 
print("Positive Sentiment %:"+" {:.2f}".format(Z2))



vectorized words

['are', 'bad', 'birthday', 'day', 'good', 'happening', 'having', 'hello', 'how', 'is', 'it', 'my', 'neither', 'nothing', 'or', 'really', 'so', 'special', 'super', 'there', 'today', 'you']

Identify Feature Words - Matrix View

[[1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 0 0 2 1 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 2 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0]]

                                             text  positive1  positive2  \
0                             Hello, how are you?          0          0   
1                            Today is a good day!          1          0   
2  It's my birthday so it's a really special day!          0          1   
3       Today is neither a good day or a bad day!          1          0   
4                           I'm having a bad day

**With NLK Sentiment Intensity Analyzer:** 

The purpose of this section is to shift from creating a manual sentiment library of words to an analyzer with a corpus alreayd established. 

In [2]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [8]:
sentences =DailyDf['comments']

In [9]:
from nltk import tokenize

In [11]:
sid = SentimentIntensityAnalyzer()
>>> for sentence in sentences:
...     print(sentence)
...     ss = sid.polarity_scores(sentence)
...     for k in sorted(ss):
...         print('{0}: {1}, '.format(k, ss[k]), end='')
...     print()

Hello, how are you?
compound: 0.0, neg: 0.0, neu: 1.0, pos: 0.0, 
Today is a good day!
compound: 0.4926, neg: 0.0, neu: 0.484, pos: 0.516, 
It's my birthday so it's a really special day!
compound: 0.5497, neg: 0.0, neu: 0.664, pos: 0.336, 
Today is neither a good day or a bad day!
compound: -0.735, neg: 0.508, neu: 0.492, pos: 0.0, 
I'm having a bad day.
compound: -0.5423, neg: 0.538, neu: 0.462, pos: 0.0, 
There' s nothing special happening today.
compound: -0.3089, neg: 0.361, neu: 0.639, pos: 0.0, 
Today is a SUPER good day!
compound: 0.8327, neg: 0.0, neu: 0.277, pos: 0.723, 


**Examples of how to complete sentiment analysis on Twitter comments:**

The purpose of this section is to examine the sentiment as they relate to some trending comments from twitter. 

In [12]:
import twitter
api = twitter.Api(consumer_key='5yVCXTUSc9YlNV8ZhKxa301PV',
  consumer_secret='5WxPIFQptDTOrR2vO65lbajjlg6LwzhIFQ5vRr8q3Z9sau4NuY',
    access_token_key='1245795441003974656-AXifRFL7o9MhyU6uT3tltrab1rY7Ga',
    access_token_secret='GarNU7M6CMjGNemtRkXQyjivkNHrc7cQqQ9URbv2F0rI8')

In [33]:
tweets=api.GetSearch(term='Breonna Taylor', since=2016-11-21, count=10)
tweets

[Status(ID=1308831501275009032, ScreenName=jemelehill, Created=Wed Sep 23 18:12:01 +0000 2020, Text='The state of Kentucky deemed the lives of Breonna Taylor’s neighbors to be worth more than her own. Let that sink in.'),
 Status(ID=1308838463282835457, ScreenName=YaraShahidi, Created=Wed Sep 23 18:39:41 +0000 2020, Text="What is most insulting is that the recommended charges aren't even in response to the MURDER of Breonna Taylor, but… https://t.co/KmFOC721JJ"),
 Status(ID=1308843681668046848, ScreenName=ClintSmithIII, Created=Wed Sep 23 19:00:25 +0000 2020, Text="I'm thinking of all the ppl who knew Breonna Taylor before she became hashtag. The people who raised her, the peopl… https://t.co/ikWXAONzWg"),
 Status(ID=1308952761925427201, ScreenName=mandeeeeee0, Created=Thu Sep 24 02:13:52 +0000 2020, Text='RT @sasquatchstacy: if you used "arrest the killers of breonna taylor" as a caption on a selfie post, you better be sending buckets of mone…'),
 Status(ID=1308952761807953920, Screen

In [34]:
dfBreonnaTaylor_Tweets=pd.DataFrame (data=[tweet.text for tweet in tweets], columns = ['Text'])

In [35]:
BTSentences= dfBreonnaTaylor_Tweets['Text']

In [37]:
sid = SentimentIntensityAnalyzer()
>>> for sentence in BTSentences:
...     print(sentence)
...     ss = sid.polarity_scores(sentence)
...     for k in sorted(ss):
...         print('{0}: {1}, '.format(k, ss[k]), end='')
...     print()

The state of Kentucky deemed the lives of Breonna Taylor’s neighbors to be worth more than her own. Let that sink in.
compound: 0.2263, neg: 0.0, neu: 0.917, pos: 0.083, 
What is most insulting is that the recommended charges aren't even in response to the MURDER of Breonna Taylor, but… https://t.co/KmFOC721JJ
compound: -0.8814, neg: 0.37, neu: 0.57, pos: 0.06, 
I'm thinking of all the ppl who knew Breonna Taylor before she became hashtag. The people who raised her, the peopl… https://t.co/ikWXAONzWg
compound: 0.0, neg: 0.0, neu: 1.0, pos: 0.0, 
RT @sasquatchstacy: if you used "arrest the killers of breonna taylor" as a caption on a selfie post, you better be sending buckets of mone…
compound: -0.5859, neg: 0.226, neu: 0.676, pos: 0.098, 
RT @sethdunlap: Louisville Police now saying, “We’re going to arrest every single person who is here right now.”  There are thousands of pe…
compound: -0.34, neg: 0.098, neu: 0.902, pos: 0.0, 
RT @RexChapman: Guys, never forget that Breonna Taylor’s k

**Discussion:** 

As very much expected, there is a lot of social unrest toward Breonna Taylors death and sentiment here shows that. 